### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by bazickoff** [boypt/cloud-torrent#1]
hello 
when I search for torrents I get this message "certificate signed by unknown authority"

website address http://167.71.74.241:3000/

**Comment by boypt** [comment]
works fine on my instance.

I guessed the reason is that you are running cloud-torrent on an old
distribution without updated `*ca*-*certificates*` package, eg centos6.

go defaultlly use the system ca certificates to validate other https
servers, if the system certificates are not updated, such errors will raise.

bazickoff <notifications@github.com> 于 2019年7月28日周日 23:02写道：

**Comment by boypt** [comment]
![image](https://user-images.githubusercontent.com/1033514/62262813-a4635c00-b44c-11e9-90d3-47ae6f148bbd.png)
